"""Noise-figure normalization for the lna-sparam-nf bench (issue #22).

Pure Python, no simulator. Two jobs:

* the analytic definition the bench's tb.json ``nf_db_*`` expressions
  implement (:func:`f_from_added_noise`, :func:`nf_db`), plus a faithful
  evaluator for those exact expression strings (:func:`eval_manifest_nf`) so
  a test can pin the manifest text to the definition;
* the comparison of a corrected campaign against the superseded record's
  per-corner logs (:func:`compare_to_superseded`).

Method. The reference source Rs1 is noiseless (``noisy=0``); ngspice's
``inoise_spectrum`` is then the input-referred noise density (V/rtHz) of
everything else, and the source's own thermal noise is added analytically at
an explicit T0:

    F = 1 + inoise_spectrum^2 / (4 k T0 Z0),    NF_dB = 10 log10 F

The superseded record used ``Rs1 ... TEMP=27`` with the plain formula
F = inoise^2 / (4 k T0 Z0). In ngspice-46 that resistor generates noise at
327.15 K (instance temp= is an offset on the Kelvin scale), so
F_old = F_true + (327.15 - 300.15) / 300.15.
"""

from __future__ import annotations

import math
import re
from pathlib import Path

K_BOLTZMANN = 1.380649e-23
T0_K = 300.15
Z0_OHM = 50.0
#: Source temperature actually generated by the former `Rs1 ... TEMP=27`
#: override in ngspice-46 (T + 300.15 K with T = 27; see the bench README).
LEGACY_SOURCE_K = 327.15
LEGACY_F_BIAS = (LEGACY_SOURCE_K - T0_K) / T0_K  # = 27 / 300.15 = 0.089955...

FREQ_SUFFIXES = ("lo", "mid", "hi")


def noise_ref_w_per_hz() -> float:
    """4 k T0 Z0 -- the noise-voltage-squared density of a Z0 source at T0."""
    return 4.0 * K_BOLTZMANN * T0_K * Z0_OHM


def f_from_added_noise(inoise_v_per_rthz: float) -> float:
    """Noise factor from a noiseless-source input-referred noise density."""
    _require_finite(inoise_v_per_rthz, "inoise")
    return 1.0 + inoise_v_per_rthz ** 2 / noise_ref_w_per_hz()


def nf_db(inoise_v_per_rthz: float) -> float:
    return 10.0 * math.log10(f_from_added_noise(inoise_v_per_rthz))


def legacy_f(inoise_v_per_rthz: float) -> float:
    """What the former noisy-source method reports for the same circuit
    (source at LEGACY_SOURCE_K, plain inoise^2/(4 k T0 Z0))."""
    _require_finite(inoise_v_per_rthz, "inoise")
    return inoise_v_per_rthz ** 2 / noise_ref_w_per_hz()


def legacy_f_from_true_f(f_true: float) -> float:
    return f_true + LEGACY_F_BIAS


def true_f_from_legacy_db(nf_old_db: float) -> float:
    """F corrected from a superseded record's NF in dB (linear-F relation)."""
    _require_finite(nf_old_db, "nf_old_db")
    return 10.0 ** (nf_old_db / 10.0) - LEGACY_F_BIAS


def _require_finite(value: float, what: str) -> None:
    if not math.isfinite(value):
        raise ValueError(f"{what} is not finite: {value!r}")


_VEC_RE = re.compile(r"noise2\.inoise_spectrum\[(\d+)\]")


def eval_manifest_nf(expression: str, spectrum: list[float]) -> float:
    """Evaluate a tb.json NF measurement expression on a given spectrum.

    The expression is ngspice syntax restricted to ``+ - * / ( )``,
    numbers, ``log10`` and the ``noise2.inoise_spectrum[i]`` vector; anything
    else is rejected rather than guessed at. A non-finite result is an error
    (a measurement must never silently become NaN/inf)."""
    for v in spectrum:
        _require_finite(v, "spectrum value")
    py = _VEC_RE.sub(lambda m: repr(spectrum[int(m.group(1))]), expression)
    py = py.replace("log10(", "math.log10(")
    leftover = re.sub(r"math\.log10|[0-9eE.+\-*/() ]", "", py)
    if leftover:
        raise ValueError(f"unsupported token(s) {leftover!r} in expression {expression!r}")
    value = eval(py, {"__builtins__": {}, "math": math})  # noqa: S307 - validated above
    _require_finite(value, f"result of {expression!r}")
    return value


# ---------------------------------------------------------------------------
# Comparison with the superseded record's per-corner logs
# ---------------------------------------------------------------------------

#: Tolerances for the corrected-vs-superseded comparison. Logs print 10
#: significant digits (`set numdgt=10`), i.e. ~1e-9 relative on values of
#: order 1-10, so the arithmetic floor is ~1e-8. The 1e-5 gates leave about
#: three orders for solver-level differences from removing one noise source
#: and from fleet-instance differences; anything larger needs an explanation,
#: not a looser tolerance.
TOL_F = 1e-5          # linear noise factor
TOL_DB = 1e-5         # S-parameters, dB
TOL_K = 1e-5          # stability factor k (absolute)

_MEAS_RE = re.compile(r"^\s*m_(\w+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)\s*$")


def parse_log(text: str) -> dict[str, float]:
    out: dict[str, float] = {}
    for line in text.splitlines():
        m = _MEAS_RE.match(line)
        if m:
            out[m.group(1)] = float(m.group(2))
    return out


def compare_to_superseded(new: dict[str, dict[str, float]], old_log_dir: Path) -> dict:
    """Compare corrected measurements (``corner_id -> {name: value}``) with the
    superseded record's logs. Returns worst-case deltas and any problems.

    NF: ``F_new`` must equal ``10^(NF_old/10) - 27/300.15`` (linear-F relation,
    NOT a constant dB offset). S-parameters and k must be unchanged."""
    worst = {"nf_f": 0.0, "nf_db": 0.0, "sparam_db": 0.0, "k": 0.0}
    problems: list[str] = []
    compared = 0
    for corner_id, meas in sorted(new.items()):
        log = old_log_dir / f"{corner_id}.log"
        if not log.is_file():
            problems.append(f"{corner_id}: no superseded log {log.name}")
            continue
        old = parse_log(log.read_text())
        for name, value in sorted(meas.items()):
            if name not in old:
                problems.append(f"{corner_id}: superseded log has no m_{name}")
                continue
            compared += 1
            if name.startswith("nf_db_"):
                f_new = 10.0 ** (value / 10.0)
                f_exp = true_f_from_legacy_db(old[name])
                worst["nf_f"] = max(worst["nf_f"], abs(f_new - f_exp))
                worst["nf_db"] = max(worst["nf_db"], abs(value - 10.0 * math.log10(f_exp)))
            elif name.startswith("k_"):
                worst["k"] = max(worst["k"], abs(value - old[name]))
            else:
                worst["sparam_db"] = max(worst["sparam_db"], abs(value - old[name]))
    for key, tol in (("nf_f", TOL_F), ("sparam_db", TOL_DB), ("k", TOL_K)):
        if worst[key] > tol:
            problems.append(f"max |d{key}| = {worst[key]:.3g} exceeds tolerance {tol:g}")
    return {"compared": compared, "worst": worst, "problems": problems,
            "tolerances": {"nf_f": TOL_F, "sparam_db": TOL_DB, "k": TOL_K}}
