#!/usr/bin/env python3
"""klt-sim driver for the lna-sparam-nf bench (issue #22).

    python3 sim/lna-sparam-nf/run.py characterize --supersedes ID [--dry-run]
    python3 sim/lna-sparam-nf/run.py ingest REPORT.json [...] --supersedes ID

`harness.cli run` simulates the 27-point grid as a LOCAL loop of `ngspice -b`
processes. On a shared dispatch host that grid goes to the off-host batch
fleet instead: this driver expresses it as `klt sim` requests (one per supply
value, 9 process x temperature corners each), then ingests the returned
per-corner logs into an ordinary harness-native record (corners/<id>/*.log,
netlist-snapshots/<id>.spice, records/<id>.md), exactly the layout
check_evidence_formats.py expects for this bench. The pattern is the one
sim/hbt-kaband-characterization/run.py established.

Ingest refuses to write unless all 27 points are present with finite values
for every declared measurement, and (when --supersedes is given) unless the
corrected values agree with the superseded record's logs under the linear-F
relation of lna_nf.py.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import math
import shlex
import subprocess
import sys
from pathlib import Path

BENCH_DIR = Path(__file__).resolve().parent
SIM_DIR = BENCH_DIR.parent
REPO_ROOT = SIM_DIR.parent
sys.path.insert(0, str(SIM_DIR))
sys.path.insert(0, str(BENCH_DIR))

import lna_nf  # noqa: E402
from harness import evidence as evidence_mod  # noqa: E402
from harness.corners import CORNERS, PvtPoint, build_grid, resolve_corners, supply_points  # noqa: E402
from harness.pdk import PdkConfigError, PdkNotFound, find_pdk  # noqa: E402
from harness.report import (  # noqa: E402
    RecordExists, allocate_record_id, build_record, git_provenance, write_netlist_snapshot,
    write_record,
)
from harness.runner import PointResult, ngspice_version  # noqa: E402
from harness.testbench import load  # noqa: E402

SCRATCH = BENCH_DIR / "_build"


def klt_body(tb, vdd: float) -> str:
    """Self-contained klt circuit body for one supply value: the PVT params,
    the fixture text and the bench's own .control block (same analyses and
    `let m_*`/`print m_*` lines harness.runner.compose_deck would emit)."""
    lines = [
        f"* {tb.name}: klt sim body, supply {vdd:.2f} V -- GENERATED by run.py, do not edit",
        f".param vdd_nom={tb.nominal_supply_v!r}",
        f".param vdd_val={vdd!r}",
    ]
    lines += [f".param {k}={v}" for k, v in tb.params.items()]
    lines += ["", tb.netlist.read_text(), "", ".control", "set numdgt=10", "set noaskquit"]
    lines += [f"  {a}" for a in tb.analyses]
    lines += [f"  let m_{n} = {e}" for n, e in tb.measure.items()]
    lines += [f"  print m_{n}" for n in tb.measure]
    lines += [".endc", ""]
    return "\n".join(lines)


def klt_request(body_name, corners, temps, backend, timeout_s, stage_models, runner_version_check):
    """One klt sim request. klt's own analysis is a 2 ps transient whose only
    purpose is a `.meas tran` sentinel on the supply rail (valid for the older
    klt 0.5.0 fleet runner too); the body's own .control block runs the real
    analyses first, as in the Ka-band driver."""
    req = {
        "netlist": body_name,
        "backend": backend,
        "models": {"pdk": "ihp-sg13g2", "lib": "libs.tech/ngspice/models/cornerHBT.lib"},
        "corners": {"process": [c.name for c in corners], "temperature_c": list(temps)},
        "analysis": {"kind": "tran", "args": "1p 2p"},
        "measurements": [
            {"name": "lna_rail_v", "spice": ".meas tran lna_rail_v FIND v(vdd) AT=2p", "unit": "V"},
        ],
        "options": {"timeout_s": timeout_s, "keep_artifacts": True},
    }
    if stage_models:
        req["options"]["stage_model_inputs"] = True
    if backend == "batch" and runner_version_check:
        req["batch"] = {"runner_version_check": runner_version_check}
    return req


def _pdk():
    try:
        return find_pdk(SIM_DIR)
    except (PdkNotFound, PdkConfigError) as exc:
        raise SystemExit(f"error: {exc}")


def cmd_characterize(args) -> int:
    tb = load(BENCH_DIR)
    corners = resolve_corners(list(tb.corners))
    supplies = supply_points(tb.nominal_supply_v, tb.supply_tolerance)
    temps = list(tb.temperatures_c)
    stamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y%m%d-%H%M%S")
    work = (SCRATCH / f"klt-{stamp}").resolve()
    work.mkdir(parents=True, exist_ok=True)
    reports = []
    for vdd in supplies:
        tag = f"{vdd:.2f}v"
        body = work / f"body_{tag}.spice"
        body.write_text(klt_body(tb, vdd))
        req = work / f"request_{tag}.json"
        req.write_text(json.dumps(klt_request(
            body.name, corners, temps, args.backend, args.timeout_s,
            not args.no_stage_models, args.runner_version_check), indent=2) + "\n")
        out, resp = work / f"out_{tag}", work / f"report_{tag}.json"
        cmd = shlex.split(args.klt_cmd) + ["sim", str(req), "--backend", args.backend,
                                           "-o", str(out), "--format", "json"]
        print("$ " + " ".join(cmd), flush=True)
        if args.dry_run:
            continue
        with resp.open("w") as fh:
            proc = subprocess.run(cmd, stdout=fh, stderr=subprocess.PIPE, text=True)
        if proc.stderr:
            (work / f"stderr_{tag}.log").write_text(proc.stderr)
        print(f"  klt exit {proc.returncode}; report {resp}", flush=True)
        if proc.returncode != 0:
            print(proc.stderr[-4000:], file=sys.stderr)
            print(f"characterize: klt sim failed for supply {tag} (exit {proc.returncode}); "
                  f"no record written. Requests/bodies kept under {work}", file=sys.stderr)
            return 1
        reports.append((vdd, resp))
    if args.dry_run:
        print(f"--dry-run: requests and bodies written under {work}; nothing submitted")
        return 0
    return ingest(tb, reports, args)


def _body_supply(body: Path) -> float:
    for line in body.read_text().splitlines():
        if line.startswith(".param vdd_val="):
            return float(line.split("=", 1)[1])
    raise SystemExit(f"error: no .param vdd_val in {body}")


def cmd_ingest(args) -> int:
    tb = load(BENCH_DIR)
    reports = []
    for path in args.reports:
        path = Path(path).resolve()
        body = path.with_name(path.name.replace("report_", "body_").replace(".json", ".spice"))
        reports.append((_body_supply(body), path))
    return ingest(tb, reports, args)


def ingest(tb, reports, args) -> int:
    pdk = _pdk()
    started = _dt.datetime.now(_dt.timezone.utc)
    git = git_provenance(REPO_ROOT)
    expected = {p.corner_id: p for p in build_grid(
        resolve_corners(list(tb.corners)), tb.temperatures_c,
        supply_points(tb.nominal_supply_v, tb.supply_tolerance))}
    problems: list[str] = []
    results: dict[str, PointResult] = {}
    texts: dict[str, str] = {}
    klt_meta = []
    for vdd, resp_path in reports:
        report = json.loads(resp_path.read_text())
        if "corners" not in report:
            problems.append(f"{resp_path.name}: no corners in klt report ({report.get('error')})")
            continue
        env = report.get("environment", {})
        klt_meta.append({"supply_v": vdd, "status": report.get("status"), "environment": env,
                         "klt_version": (report.get("provenance") or {}).get("klt_version")})
        for corner in report["corners"]:
            point = PvtPoint(corner=CORNERS[corner["process"]],
                             temp_c=float(corner["temperature_c"]), vdd=float(vdd))
            log = (corner.get("artifacts") or {}).get("log")
            if not log:
                problems.append(f"{point.corner_id}: klt returned no log ({corner.get('diagnostics')})")
                continue
            log_path = Path(log)
            if not log_path.is_absolute():
                log_path = (resp_path.parent / log_path).resolve()
            text = log_path.read_text()
            meas = lna_nf.parse_log(text)
            missing = [n for n in tb.measure if n not in meas]
            nonfinite = [n for n, v in meas.items() if not math.isfinite(v)]
            if missing or nonfinite:
                problems.append(f"{point.corner_id}: missing {missing} / non-finite {nonfinite}")
                continue
            texts[point.corner_id] = text
            results[point.corner_id] = PointResult(
                point=point, status="ok", measurements={n: meas[n] for n in tb.measure},
                seconds=float(corner.get("runtime_s") or 0.0), deck="(klt sim body)",
                log=f"{point.corner_id}.log")
    missing_pts = sorted(set(expected) - set(results))
    if missing_pts:
        problems.append("missing PVT points: " + ", ".join(missing_pts))
    comparison = None
    if not problems and args.supersedes:
        old_dir = tb.experiment_dir / "corners" / args.supersedes
        comparison = lna_nf.compare_to_superseded(
            {cid: r.measurements for cid, r in results.items()}, old_dir)
        print(f"comparison with {args.supersedes}: {comparison['compared']} values compared; "
              f"worst {comparison['worst']}")
        problems += comparison["problems"]
    if problems:
        for p in problems[:40]:
            print(f"FAIL: {p}", file=sys.stderr)
        print("ingest: grid incomplete or invalid; NO record written", file=sys.stderr)
        return 1

    client = subprocess.run(shlex.split(args.klt_cmd) + ["--version"], capture_output=True, text=True)
    client_v = (client.stdout or client.stderr).strip()
    engines = sorted({str(m["environment"].get("engine_version")) for m in klt_meta})
    notes = list(tb.evidence.notes)
    notes.append(
        "CORRECTION RECORD (issue #22): this record supersedes "
        f"{args.supersedes or '(none)'} and is a FRESH simulation of the full 27-point HBT x T x V "
        "grid with the corrected NF method (noiseless Rs1, analytic F = 1 + inoise^2/(4 k 300.15 K Z0)); "
        "it is not a reprocessing of the old logs. The old record is untouched.")
    if comparison:
        w, t = comparison["worst"], comparison["tolerances"]
        notes.append(
            f"Comparison with the superseded logs ({comparison['compared']} values over 27 corners): "
            f"F_new vs 10^(NF_old/10) - 27/300.15 agrees to max |dF| = {w['nf_f']:.3g} "
            f"(tolerance {t['nf_f']:g}; printed precision is 10 significant digits); "
            f"S-parameters max |d| = {w['sparam_db']:.3g} dB (tol {t['sparam_db']:g}); "
            f"k max |d| = {w['k']:.3g} (tol {t['k']:g}). The NF shift is a constant 27/300.15 = "
            f"{lna_nf.LEGACY_F_BIAS:.6f} in linear F, not a constant dB offset.")
    for m in klt_meta:
        e = m["environment"]
        remote = dict(e.get("remote") or {})
        notes.append(
            f"klt sim at supply {m['supply_v']:.2f} V: status {m['status']}, client `{client_v}`, "
            f"engine {e.get('engine')} {e.get('engine_version')}, models_lib_sha256 "
            f"{e.get('models_lib_sha256')}, remote job {remote.get('job_id')} "
            f"({remote.get('provider')}, {remote.get('instance_type')}, runner klt "
            f"{remote.get('runner_klt_version')} vs client {remote.get('client_klt_version')}, "
            f"compatibility {remote.get('runner_compatibility')}).")
    notes.append(
        f"Simulation host: klt sim engine ngspice {', '.join(engines)} (off-host); the ingesting "
        f"host's own ngspice ({ngspice_version()}) did NOT produce these numbers and is recorded "
        "only as the ingest environment. No local re-simulation cross-check is possible on that "
        "version (the instance resistor temp= behaviour that motivated this correction is "
        "specific to ngspice-46; on the ingesting host's version the old and new methods agree).")
    extensions = evidence_mod.BaseExtensions(
        record_kind=tb.evidence.record_kind, data_provenance=tb.evidence.data_provenance,
        extra=dict(tb.evidence.extra), notes=notes)
    extensions.validate()

    record_id = allocate_record_id(REPO_ROOT, tb.experiment_dir / "records", started, git)
    log_dir = tb.experiment_dir / "corners" / record_id
    if log_dir.exists():
        raise RecordExists(f"{log_dir} exists; append-only evidence is never rewritten")
    log_dir.mkdir(parents=True)
    for cid, text in sorted(texts.items()):
        (log_dir / f"{cid}.log").write_text(text)
    points = [expected[cid] for cid in sorted(expected)]
    ordered = [results[p.corner_id] for p in points]
    wall = (_dt.datetime.now(_dt.timezone.utc) - started).total_seconds()
    record = build_record(
        tb, pdk, points, ordered, f"{', '.join('ngspice-' + e for e in engines)} via klt sim "
        f"(ingested on {ngspice_version()})", REPO_ROOT, record_id, started.isoformat(), wall,
        claim=args.claim or tb.claim, supersedes=args.supersedes or "", git=git,
        extensions=extensions)
    write_netlist_snapshot(tb, tb.experiment_dir, record_id)
    path = write_record(record, tb.experiment_dir)
    print(f"wrote {path}")
    return 0 if record["status"] == "pass" else 1


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="command", required=True)
    pc = sub.add_parser("characterize")
    pc.add_argument("--klt-cmd", default="klt")
    pc.add_argument("--backend", default="batch")
    pc.add_argument("--timeout-s", type=int, default=1800)
    pc.add_argument("--no-stage-models", action="store_true")
    pc.add_argument("--runner-version-check", default="", choices=("", "enforce", "warn"))
    pc.add_argument("--claim", default="")
    pc.add_argument("--supersedes", default="")
    pc.add_argument("--dry-run", action="store_true")
    pc.set_defaults(func=cmd_characterize)
    pi = sub.add_parser("ingest")
    pi.add_argument("reports", nargs="+")
    pi.add_argument("--klt-cmd", default="klt")
    pi.add_argument("--claim", default="")
    pi.add_argument("--supersedes", default="")
    pi.set_defaults(func=cmd_ingest)
    return p


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
