#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""`fit` stage: fit a lumped `.subckt` to the de-embedded p1 baseline run.

Adapted (p1 only; standalone absolute-valued subcircuit instead of an
analytic-times-correction model) from the sibling `fit_lumped.py`, pinned in
../INPUTS.json (original under ../upstream/).  The 2-pi topology and the split
fit (series impedance / shunt admittance) are the sibling's; the analytic
element expressions are kept ONLY to seed the optimiser's starting point.  They
never enter the fitted result, so no sibling number is carried across.

Writes  <dir>/fit/p1_fit_parameters.json   <dir>/fit/p1_fit_candidate.spice
Exit    0 fit produced (quality is judged by `compare`); 4 FIT_FAILED
        (optimiser failure, non-physical element, or parameter pinned at its
        bound); 3 no baseline data; 2 malformed data.
"""

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import emlib  # noqa: E402
import p1chain as C  # noqa: E402

FIT_FLO = 0.3e9
FIT_FHI = 30e9
SRF_MARGIN = 0.85
LB_S = np.array([1e-3, 1e-3, 1e-15, 1e-12, 1e-18])
UB_S = np.array([1e4, 1e6, 1e-6, 1e-6, 1e-12])
LB_H = np.array([1e-18, 1e-2, 1e-18])
UB_H = np.array([1e-9, 1e7, 1e-9])

# --- starting-point heuristics only (see module docstring) -------------------
MU0 = 1.25663706212e-6
EPS0 = 8.8541878128e-12
KOCT = 3.31370849898476
AOCT = 0.828427124746190


def seed(w, d, n=1):
    """Order-of-magnitude seeds for the optimiser (NOT results)."""
    dout = d + 2 * w
    davg = (d + dout) / 2
    fill = (dout - d) / (dout + d)
    ln = KOCT * n * (d + w)
    ltot = 2.25 * MU0 * n * n * davg / (1 + 3.55 * fill)
    rdc = 11e-3 * ln / (w - 0.14e-6)
    aout = AOCT * dout * dout
    aeq = np.sqrt(aout / np.pi)
    return {"Rser": rdc, "Rlad": 2 * rdc, "L1": MU0 * ln * 3e-6 / (2 * w) / 9.8696,
            "Ltot": ltot, "Cs": 1e-18 * 10, "Cox": (AOCT * (dout ** 2 - d ** 2) * 3.233e-6) / 2,
            "Rsub": 1.41421356237 * 0.5 / (4 * aeq), "Csub": 5e-15}


def _resid(model, meas, floor_frac=0.02):
    floor = floor_frac * np.max(np.abs(meas))
    r = (model - meas) / (np.abs(meas) + floor)
    return np.concatenate([r.real, r.imag])


def fit(f, Zd):
    from scipy.optimize import least_squares
    Y = emlib.z2y(Zd)
    ys_meas, yh_meas = emlib.measured_series_shunt(Y)
    g = seed(8.22e-6, 47.65e-6)
    zs_meas = 1.0 / ys_meas

    x0 = np.clip(np.array([g["Rser"], g["Rlad"], g["L1"], g["Ltot"], g["Cs"]]),
                 LB_S * 1.001, UB_S * 0.999)
    sol_s = least_squares(
        lambda lx: _resid(1.0 / emlib.y_series(f, *np.exp(lx)), zs_meas),
        np.log(x0), bounds=(np.log(LB_S), np.log(UB_S)),
        xtol=1e-14, ftol=1e-14, gtol=1e-14, max_nfev=20000)
    x0h = np.clip(np.array([g["Cox"], g["Rsub"], g["Csub"]]), LB_H * 1.001, UB_H * 0.999)
    sol_h = least_squares(
        lambda lx: _resid(emlib.y_shunt(f, *np.exp(lx)), yh_meas),
        np.log(x0h), bounds=(np.log(LB_H), np.log(UB_H)),
        xtol=1e-14, ftol=1e-14, gtol=1e-14, max_nfev=20000)
    ps = dict(zip(("Rser", "Rlad", "L1", "Ltot", "Cs"), np.exp(sol_s.x)))
    ph = dict(zip(("Cox", "Rsub", "Csub"), np.exp(sol_h.x)))
    return ps, ph, sol_s, sol_h


def pinned(sol, lb, ub, names):
    x = np.exp(sol.x)
    return [n for n, v, lo, hi in zip(names, x, lb, ub)
            if v <= lo * 1.0001 or v >= hi * 0.9999]


def write_spice(path, ps, ph, fit_band, srf_em):
    lm = [ps["L1"] / m ** 2 for m in range(1, 11)]
    lmain = ps["Ltot"] - sum(lm)
    L = ["* sg13g2 p1 single-turn inductor2 (w=8.22u s=3.29u d=47.65u nr_r=1) -- LUMPED FIT",
         "* CANDIDATE: generated by passive-p1/scripts/fit_p1.py from the de-embedded openEMS",
         "* baseline run.  Not qualified unless the append-only record that cites this file",
         "* states QUALIFIED.  Valid only for this exact geometry and only inside the tested",
         "* band; nominal EM stackup point only (no process/temperature spread).",
         "* fit band Hz: %.6g .. %.6g ; EM SRF: %s" % (fit_band[0], fit_band[1], srf_em),
         "* SPDX-License-Identifier: Apache-2.0",
         ".subckt p1_inductor_em la lb sub",
         "Rser la n02 %.9g" % ps["Rser"]]
    nodes = ["n02"] + ["n%02d" % (i + 3) for i in range(10)]
    for k in range(10):
        L.append("Rk%d %s %s %.9g" % (k + 1, nodes[k], nodes[k + 1], ps["Rlad"]))
        L.append("Lk%d %s %s %.9g" % (k + 1, nodes[k], nodes[k + 1], lm[k]))
    L += ["Lmain %s lb %.9g" % (nodes[-1], lmain),
          "Cser la lb %.9g" % ps["Cs"],
          "Coxa la n20 %.9g" % ph["Cox"], "Rsia n20 sub %.9g" % ph["Rsub"], "Csia n20 sub %.9g" % ph["Csub"],
          "Coxb lb n21 %.9g" % ph["Cox"], "Rsib n21 sub %.9g" % ph["Rsub"], "Csib n21 sub %.9g" % ph["Csub"],
          ".ends p1_inductor_em", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(L))
    return lmain


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", required=True)
    args = ap.parse_args()
    fitdir = os.path.join(args.dir, "fit")
    os.makedirs(fitdir, exist_ok=True)
    for stale in ("p1_fit_parameters.json", "p1_fit_candidate.spice"):
        p = os.path.join(fitdir, stale)
        if os.path.exists(p):
            os.remove(p)
    res = os.path.join(args.dir, "results")
    s2p = os.path.join(res, "inductor_p1.s2p")
    pinfo = os.path.join(res, "inductor_p1", "port_information.json")
    if not (os.path.isfile(s2p) and os.path.isfile(pinfo)):
        print("MISSING solver output: %s" % s2p)
        return 3
    try:
        f, S, z0 = C.read_snp_strict(s2p)
        Lport = emlib.port_inductances(json.load(open(pinfo)))
        keep = f > 0
        f, S = f[keep], S[keep]
        Zd = emlib.deembed_series_L(f, emlib.s2z(S, z0), Lport)
    except (C.DataError, np.linalg.LinAlgError, KeyError) as exc:
        print("DATA ERROR: %s" % exc)
        return 2
    srf_em = C.srf(f, emlib.z_single_ended(Zd))
    fhi = FIT_FHI if not srf_em["found"] else min(FIT_FHI, SRF_MARGIN * srf_em["hz"])
    m = (f >= FIT_FLO) & (f <= fhi)
    try:
        ps, ph, sol_s, sol_h = fit(f[m], Zd[m])
    except Exception as exc:  # optimiser failure is a FIT_FAILED outcome
        print("FIT_FAILED: optimiser raised %r" % (exc,))
        return 4
    problems = pinned(sol_s, LB_S, UB_S, ("Rser", "Rlad", "L1", "Ltot", "Cs")) + \
        pinned(sol_h, LB_H, UB_H, ("Cox", "Rsub", "Csub"))
    lm_sum = sum(ps["L1"] / k ** 2 for k in range(1, 11))
    if ps["Ltot"] - lm_sum <= 0:
        problems.append("Lmain<=0")
    out = {"geometry": "p1", "fitted": {**ps, **ph}, "fit_band_hz": [FIT_FLO, float(fhi)],
           "srf_em": srf_em, "series_cost": float(sol_s.cost), "shunt_cost": float(sol_h.cost),
           "problems": problems, "topology": "2-pi, 10-section R||L ladder, Cser, Cox+Rsub||Csub per port",
           "reference": "ports LA/LB, common reference = sub node"}
    with open(os.path.join(fitdir, "p1_fit_parameters.json"), "w") as fh:
        json.dump(out, fh, indent=2, sort_keys=True, default=str)
        fh.write("\n")
    if problems:
        print("FIT_FAILED: %s" % problems)
        return 4
    srf_txt = ("%.6g Hz" % srf_em["hz"]) if srf_em["found"] else \
        ("no crossing below %.3g Hz (lower bound only)" % srf_em["search_ceiling_hz"])
    write_spice(os.path.join(fitdir, "p1_fit_candidate.spice"), ps, ph, (FIT_FLO, fhi), srf_txt)
    print("fit ok over %.3g..%.3g GHz" % (FIT_FLO / 1e9, fhi / 1e9))
    return 0


if __name__ == "__main__":
    sys.exit(main())
